font_family FiraCode Nerd Font Mono
font_size 10.0
disable_ligatures cursor

background_opacity 0.9
confirm_os_window_close 0

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines -1
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4
# selection_foreground none
# selection_background none
# foreground #dddddd
# background #000000
# cursor #dddddd

#allow to paste remotely in nvim on jc-desktop
clipboard_control write-clipboard write-primary read-clipboard read-primary

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
