alias wu='sudo wg-quick up wg0'
alias wd='sudo wg-quick down wg0'
alias bs='killall browser-sync; cd /var/www/tubs && sudo browser-sync start --config /var/www/tubs/bs-config.js '
alias bsn='killall browser-sync; cd /var/empty && sudo browser-sync start --config /var/www/tubs/bs-config.js '
alias svd='svn diff -r BASE:HEAD'
